name: Build+Test

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - uses: actions/checkout@v3

      - name: Cache eslint
        uses: actions/cache@v4
        env:
          cache-name: cache-eslint
        with:
          path: ~/.eslintcache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.eslintrc') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.eslintrc') }}
            ${{ runner.os }}-${{ env.cache-name }}-

      # Cypress recommends to cache ~/.cache and not to cache node_modules, see
      # https://docs.cypress.io/guides/guides/continuous-integration.html#Caching
      - name: Cache
        uses: actions/cache@v4
        env:
          cache-name: cache
          cache-version: 2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ env.cache-name }}-v${{ env.cache-version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-v${{ env.cache-version }}-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-${{ env.cache-name }}-v${{ env.cache-version }}-

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Cypress Browser Tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: pnpm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180
        # Uncomment to enable i18n debug logging which will be shown in the step logs.
        # env:
        #   REACT_APP_DEBUG: ON

      - name: Archive Cypress screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*
          retention-days: 5

      - name: Archive Cypress videos
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*
          retention-days: 5
