name: Build+Test

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Cypress Browser Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: pnpm start
          wait-on: 'http://localhost:5173/'
          wait-on-timeout: 30
        # Uncomment to enable i18n debug logging which will be shown in the step logs.
        # env:
        #   REACT_APP_DEBUG: ON

      - name: Archive Cypress screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*
          retention-days: 5

      - name: Archive Cypress videos
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*
          retention-days: 5
